---
- hosts: dankpad # Specify from inventory file.
  remote_user: root

  vars:
      master_ip: RELIABLE_IP_HERE

  tasks:
      - name: SaltBootstrap-OneLiner
        shell: python -c "import urllib2; print urllib2.urlopen('https://bootstrap.saltstack.com').read()" > bs.sh && sh bs.sh -A {{ master_ip }}
        tags:
            - Bootstrap

      - name: Restart_Salt
        command: reboot
        tags:
            - restart
